### ISSUE TITLE
Credits/License

### ISSUE THREAD

**Issue by michaelbull** [Trevelopment/vlc-super-skipper#1]
Hi. It seems this repository has derived a lot of code from my [`vlc-credit-skipper`](https://github.com/michaelbull/vlc-credit-skipper) repository and is missing any attribution of authoring to myself and the LICENSE file that accompanies the code. It is very clearly derived from this repository given the exact 1:1 code snippets, identical method names, and regex patterns.

I have listed a few examples of copied functions beneath, however other snippets of code within bigger functions have also been copied directly. Also the README seems to be heavily lifted from my repository, both in structure and wording.

Please can you add the necessary [ISC License from my original repository](https://github.com/michaelbull/vlc-credit-skipper/blob/master/LICENSE) that must be kept in instances that the code has been copied/modified/derived from? Failure to include this license within this repository do this will be in violation of the license that the infringing code was derived from. The license in full can be found [here](https://github.com/michaelbull/vlc-credit-skipper/blob/master/LICENSE)

I would also appreciate some accreditation for the work I've done towards this repository, as neither my name nor my original repository receives any mention anywhere on here. I can't realistically compel you to do this, but it would be appreciated.

Thanks for your cooperation.

---

### `function populate_profile_dropdown`

- Mine [vlc-credit-skipper/credit-skipper.lua lines 70-76](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L70-L76):

```lua
function populate_profile_dropdown()
    profile_dropdown = dialog:add_dropdown(1, 2, 2, 1)

    for i, profile in pairs(profiles) do
        profile_dropdown:add_value(profile.name, i)
    end
end
```

- Yours [vlc-super-skipper/lua/extensions/super-skipper.lua lines 160-166](https://github.com/Trevelopment/vlc-super-skipper/blob/2e5b5cece5735c33b826b7a48c5d345f5904d57e/lua/extensions/super-skipper.lua#L160-L166):

```lua
function populate_profile_dropdown()
  profile_dropdown = dlg:add_dropdown(1, 2, 4, 1)

  for i, profile in pairs(profiles) do
    profile_dropdown:add_value(profile.name, i)
  end
end
```

### `function delete_profile`

- Mine [vlc-credit-skipper/credit-skipper.lua lines 88-95](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L88-L95):

```lua
function delete_profile()
    local dropdown_value = profile_dropdown:get_value()

    if profiles[dropdown_value] then
        profiles[dropdown_value] = nil
        save_all_profiles()
    end
end
```

- Yours [vlc-super-skipper/lua/extensions/super-skipper.lua lines 183-190](https://github.com/Trevelopment/vlc-super-skipper/blob/2e5b5cece5735c33b826b7a48c5d345f5904d57e/lua/extensions/super-skipper.lua#L183-L190):

```lua
function delete_profile()
  local dropdown_value = profile_dropdown:get_value()

  if profiles[dropdown_value] then
    profiles[dropdown_value] = nil
    save_all_profiles()
  end
end
```

### `function save_all_profiles`

- Mine [vlc-credit-skipper/credit-skipper.lua lines 170-184](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L170-L184):

```lua
function save_all_profiles()
    io.output(config_file)
    for _, profile in pairs(profiles) do
        io.write(profile.name)
        io.write("=")
        io.write(profile.start_time)
        io.write(",")
        io.write(profile.finish_time)
        io.write("\n")
    end
    io.close()

    dialog:del_widget(profile_dropdown)
    populate_profile_dropdown()
end
```

- Yours [vlc-super-skipper/lua/extensions/super-skipper.lua lines 458-476](https://github.com/Trevelopment/vlc-super-skipper/blob/2e5b5cece5735c33b826b7a48c5d345f5904d57e/lua/extensions/super-skipper.lua#L458-L476)

```lua
function save_all_profiles()
  io.output(config_file)
  for _, profile in pairs(profiles) do
    io.write(profile.name)
    io.write("=")
    io.write(profile.opening_start_time)
    io.write(",")
    io.write(profile.opening_stop_time)
    io.write(",")
    io.write(profile.ending_start_time)
    io.write(",")
    io.write(profile.ending_stop_time)
    io.write("\n")
  end
  io.close()

  dlg:del_widget(profile_dropdown)
  populate_profile_dropdown()
end
```

### `function load_all_profiles`

- Mine [vlc-credit-skipper/credit-skipper.lua lines 186-198](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L186-L198):

```lua
function load_all_profiles()
    local lines = lines_from(config_file)

    for _, line in pairs(lines) do
        for name, start_time, finish_time in string.gmatch(line, "(.+)=(%d+),(%d+)") do
            table.insert(profiles, {
                name = name,
                start_time = start_time,
                finish_time = finish_time
            })
        end
    end
end
```

- Yours [vlc-super-skipper/lua/extensions/super-skipper.lua lines 478-493](https://github.com/Trevelopment/vlc-super-skipper/blob/2e5b5cece5735c33b826b7a48c5d345f5904d57e/lua/extensions/super-skipper.lua#L478-L493)

```lua
function load_all_profiles()
  local lines = lines_from(config_file)

  for _, line in pairs(lines) do
    for name, opening_start_time, opening_stop_time, ending_start_time, ending_stop_time in
    string.gmatch(line, "(.+)=(%d+),(%d+),(%d+),(%d+)") do
      table.insert(profiles, {
        name = name,
        opening_start_time = opening_start_time,
        opening_stop_time = opening_stop_time,
        ending_start_time = ending_start_time,
        ending_stop_time = ending_stop_time
      })
    end
  end
end
```

### `function file_exists`

- Mine [vlc-credit-skipper/credit-skipper.lua lines 200-204](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L200-L204):

```lua
function file_exists(file)
    local f = io.open(file, "rb")
    if f then f:close() end
    return f ~= nil
end
```

- Yours [vlc-super-skipper/lua/extensions/super-skipper.lua lines 495-501](https://github.com/Trevelopment/vlc-super-skipper/blob/2e5b5cece5735c33b826b7a48c5d345f5904d57e/lua/extensions/super-skipper.lua#L495-L501)

```lua
function file_exists(file)
  local f = io.open(file, "rb")
  if f then
    f:close()
  end
  return f ~= nil
end
```

### `function lines_from`

- Mine [vlc-credit-skipper/credit-skipper.lua lines 206-214](https://github.com/michaelbull/vlc-credit-skipper/blob/master/credit-skipper.lua#L206-L214):

```lua
function lines_from(file)
    local lines = {}

    for line in io.lines(file) do
        lines[#lines + 1] = line
    end

    return lines
end
```

- Yours [vlc-super-skipper/lua/extensions/super-skipper.lua lines 503-511](https://github.com/Trevelopment/vlc-super-skipper/blob/2e5b5cece5735c33b826b7a48c5d345f5904d57e/lua/extensions/super-skipper.lua#L503-L511)

```lua
function lines_from(file)
  local lines = {}

  for line in io.lines(file) do
    lines[#lines + 1] = line
  end

  return lines
end
```

**Comment by michaelbull** [comment]
Ping @Trevelopment

**Comment by michaelbull** [comment]
Seems like you're just going to continue to claim that my code is under your license and you've now extended to commenting on my own repository encouraging people to use yours instead. I'll close this and persue other avenues for dealing with copyright infringement.

**Comment by Trevelopment** [comment]
I will add it I just don't have time right now

**Comment by Trevelopment** [comment]
I am seeing this for the first time almost a year after you opened the issue so that shows how much time I have to dedicate to it.

**Comment by Trevelopment** [comment]
By the way, I only commented to let that user know that this addon has the functionality they were looking for.   I did use some modified snippets from your addon and some others as well but that is the beauty of open source.  I will add the license but I have to say that pursuing copyright infringement on an open source project (or threatening to do so) is one of the scummiest things I can imagine. Maybe watch this video --> [![Watch this video](https://static.fsf.org/nosvn/FSF30-video/fsf30-poster.png)](https://static.fsf.org/nosvn/FSF30-video/FSF_30_720p.webm) and try to think more in terms of copyleft instead of copyright.

**Comment by michaelbull** [comment]
> I will add it I just don't have time right now

Yet you have time to go around commenting on issues on my repository & my VLC addon's page?

>  I will add the license but I have to say that pursuing copyright infringement on an open source project (or threatening to do so) is one of the scummiest things I can imagine.

- You ignored my request for attribution for almost a full year.
- You took hundreds of lines of my code (and README) and knowlingly removed all attribution & LICENSE information.
- You relicensed my code under GPL, which is completely invalid; you can't just freely relicense ISC code as GPL and remove the original ISC license.
- You started commenting on open issues on my repository telling people to use yours instead.
- You started commenting on my VLC addons page telling people to use yours instead.

I think you need to reevaluate your own actions before calling mine 'scummy' and trying to lecture me about the spirit of opensource.

Taking other peoples opensource code, claiming it as your own, relicensing it & removing the original license, then actively trying to steer attention away from the original author's project is certainly more scummy than somebody protecting their own original works (which I am fully in my right to do given you didn't reply to any of my polite requests from a year ago).

**Comment by Trevelopment** [comment]
I don't really have time for this but I will do it to anyway.

- I started this from scratch so I can license it under whatever I want to.  Sure, I used parts of your code to make development quicker but I didn't take "hundreds of lines" of your code and if I knew you were going to be like this I would have just spent the extra time to unnecessarily rewrite the code myself.  
- You use a readme format that is simple and standard so you can't claim that as original. 
- I didn't remove any license or anything because I started this project from scratch and only added some functions from your code that worked for me.  You can find similar code in many vlc addons for dropdowns and saving and loading data to and from files so your code is also not completely original and what I did use I would have wrote similarly or possibly even the same as you did with maybe different function and/or variable names.
- I only commented on the comments that asked for specific functionality that your addon lacks so that they could find something that works better for what they need.  I am not trying to "steer attention away" from your project and even though it does something similar, the way it works is completely different.
- You need to reevaluate your actions as an open source programmer and stop being so arrogant.  Your threat to "persue [pursue] other avenues for dealing with copyright infringement" over a vlc addon is so petty.
- This is what I will include for you and you can do what you want https://github.com/Trevelopment/vlc-super-skipper/blob/master/NOTICE  it is a prerfectly acceptable way to show I used some of your code that is under a different license.
